import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import Searchbar from '../components/Searchbar';
import Navbar from '../components/Navbar';
import styles from '../styles/Home.module.css';
import Hero from '../components/Hero';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NFT Marketplace</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar></Navbar>
        <Searchbar></Searchbar>
        <CTA>
          <CTATitle>Go <StealthSpan>Stealth Mode</StealthSpan> with your <span>NFT</span> buys</CTATitle>
          <CTASubTitle>Make offers to NFT Holders without revealing identity</CTASubTitle>
        </CTA>
        <Hero></Hero>


        
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your Zick Coders at ETH3 Berlin
        </a>
      </footer>
    </div>
  );
};

const CTA = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: start;
  align-items: center;
`

const CTATitle = styled.h1`
  font-size: 50px;
  margin-bottom: 16px;
`
const CTASubTitle = styled.h2`
  margin-top: 0px;
  font-size: 30px;
`

const StealthSpan = styled.span`
  background-image: linear-gradient(124deg, #f7f5f5, #d4d4d4, #b3b3b2, #8a8a89, #696a6a, #565656, #3f3e3f, #7e7d7e, #cdccce);
  -webkit-background-clip: text;
  -moz-background-clip: text;
  background-clip: text;
  color: transparent;
  display: inline-block;
`

export default Home;
